### ISSUE TITLE
View does not auto-adjust based on expansion 

### ISSUE THREAD

**Issue by jjanelee97** [ercpereda/react-native-accordion#2]
If I click on a cell and it expands, the view should auto-adjust to the bottom border of the content that just opened.  
Right now, it doesn't seems to do that.  How can I implement this?

**Comment by ercpereda** [comment]
Can you send a screenshoot of what are you trying to do?

**Comment by jjanelee97** [comment]
<img width="429" alt="screen shot 2018-10-26 at 7 17 13 pm" src="https://user-images.githubusercontent.com/16146269/47596357-cc6cde80-d953-11e8-98ff-14f813645bb7.png">
<img width="469" alt="screen shot 2018-10-26 at 7 17 19 pm" src="https://user-images.githubusercontent.com/16146269/47596359-d0006580-d953-11e8-811d-f6d9efdfc9f6.png">
<img width="445" alt="screen shot 2018-10-26 at 7 17 27 pm" src="https://user-images.githubusercontent.com/16146269/47596361-d68edd00-d953-11e8-9dba-7f21cd12d1d7.png">

**Comment by jjanelee97** [comment]
@ercpereda you can see that when I click on a cell that is near the bottom, when it expands, you can't see the contents of the header without scrolling down.  
If I do this to the last cell of the list, then the user might miss that, so I wanted to auto-adjust the view to include the contents of the cell that was clicked.

**Comment by ercpereda** [comment]
Seems like the accordion is working fine, you will need to manage the scroll by your own. Maybe we can add a feature to manage the scroll automatically, but right now isn't implemented. A PR will be very welcome ;-)

**Comment by ercpereda** [comment]
You can use this methos of `<ScrollView />` https://facebook.github.io/react-native/docs/scrollview#scrollto and calculate where to scroll.
